version: '3.8'

services:
  panel:
    build: .
    container_name: draco-panel
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=draco
      - DB_USERNAME=draco
      - DB_PASSWORD=dracopassword

  mysql:
    image: mariadb:10.6
    container_name: draco-mysql
    restart: always
    environment:
      MYSQL_DATABASE: draco
      MYSQL_USER: draco
      MYSQL_PASSWORD: dracopassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
